import { Menu } from "@/types/Menu";

export const menuData: Menu[] = [
  {
    id: 1,
    title: "Popular",
    titleKey: "popular",
    newTab: false,
    path: "/",
  },
  {
    id: 2,
    title: "Shop",
    titleKey: "shop",
    newTab: false,
    path: "/shop-with-sidebar",
  },
  {
    id: 3,
    title: "Contact",
    titleKey: "contact",
    newTab: false,
    path: "/contact",
  },
  {
    id: 6,
    title: "pages",
    titleKey: "pages",
    newTab: false,
    path: "/",
    submenu: [
      {
        id: 61,
        title: "Shop With Sidebar",
        titleKey: "shopWithSidebar",
        newTab: false,
        path: "/shop-with-sidebar",
      },
      {
        id: 62,
        title: "Shop Without Sidebar",
        titleKey: "shopWithoutSidebar",
        newTab: false,
        path: "/shop-without-sidebar",
      },
      {
        id: 64,
        title: "Checkout",
        titleKey: "checkout",
        newTab: false,
        path: "/checkout",
      },
      {
        id: 65,
        title: "Cart",
        titleKey: "cart",
        newTab: false,
        path: "/cart",
      },
      {
        id: 66,
        title: "Wishlist",
        titleKey: "wishlist",
        newTab: false,
        path: "/wishlist",
      },
      {
        id: 67,
        title: "Sign in",
        titleKey: "signIn",
        newTab: false,
        path: "/signin",
      },
      {
        id: 68,
        title: "Sign up",
        titleKey: "signUp",
        newTab: false,
        path: "/signup",
      },
      {
        id: 69,
        title: "My Account",
        titleKey: "myAccount",
        newTab: false,
        path: "/my-account",
      },
      {
        id: 70,
        title: "Contact",
        titleKey: "contact",
        newTab: false,
        path: "/contact",
      },
      {
        id: 62,
        title: "Error",
        titleKey: "error",
        newTab: false,
        path: "/error",
      },
      {
        id: 63,
        title: "Mail Success",
        titleKey: "mailSuccess",
        newTab: false,
        path: "/mail-success",
      },
    ],
  },
  {
    id: 7,
    title: "blogs",
    titleKey: "blogs",
    newTab: false,
    path: "/",
    submenu: [
      {
        id: 71,
        title: "Blog Grid with sidebar",
        titleKey: "blogGridWithSidebar",
        newTab: false,
        path: "/blogs/blog-grid-with-sidebar",
      },
      {
        id: 72,
        title: "Blog Grid",
        titleKey: "blogGrid",
        newTab: false,
        path: "/blogs/blog-grid",
      },
      {
        id: 73,
        title: "Blog details with sidebar",
        titleKey: "blogDetailsWithSidebar",
        newTab: false,
        path: "/blogs/blog-details-with-sidebar",
      },
      {
        id: 74,
        title: "Blog details",
        titleKey: "blogDetails",
        newTab: false,
        path: "/blogs/blog-details",
      },
    ],
  },
];
